import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, ArrowDown, ArrowLeft } from 'lucide-react';
import { Header, Footer, DomainDiagram } from '../site-components';
export const metadata:Metadata={title:'Assess — Find your next edge',description:'Explore an adaptive AI competency assessment framework: seven domains, five levels, and a personalized path for professional development. Based on SAICA.'};
const domains=[['Foundational concepts','Understand how models work, where their limits lie, and what their parameters change.'],['Prompting','Frame requests, supply useful context, and improve an approach when the result falls short.'],['Workflow design','Connect steps, tools, and human checkpoints into a process that works.'],['Ethics and risk','Recognize bias, protect privacy, and judge when the risks outweigh the benefits.'],['Tool selection','Match the model, tool, or approach to the task and its constraints.'],['Output evaluation','Check evidence, detect unreliable claims, and judge the quality of a result.'],['Metacognition','Examine your assumptions, calibrate your confidence, and reflect on your own reasoning.']];
const levels=[['01','The Copy-Paster','Uses AI output with limited checking or adaptation.'],['02','The Prompt Crafter','Prompts deliberately and improves results through iteration.'],['03','The Maker','Connects tools and critically evaluates multi-step work.'],['04','The Engineer','Builds reliable workflows with safeguards and clear trade-offs.'],['05','The Orchestrator','Designs, evaluates, and improves AI systems for others.']];
export default function Assess(){return <><Header active="assess"/><main id="main"><section className="detail-hero wrap assess-hero"><Link href="/" className="back-link"><ArrowLeft size={15}/> All projects</Link><div className="detail-title-row"><span className="eyebrow">02 / Assess</span><span className="status"><i/> Based on the SAICA framework</span></div><div className="detail-grid"><div><h1>Find your<br/><em>next edge.</em></h1><p className="detail-lead">Knowing how to prompt is one part of the picture. Understand your AI skills, your judgment, and where to grow next.</p><a href="#framework" className="button ink">Explore the framework <ArrowDown size={18}/></a></div><div className="detail-visual"><span className="eyebrow">AI COMPETENCE / SEVEN DIMENSIONS</span><DomainDiagram/></div></div><div className="assessment-stats"><div><strong>7</strong><span>Domains of competence</span></div><div><strong>12</strong><span>Adaptive questions per session</span></div><div><strong>~20<span> min</span></strong><span>Designed assessment length</span></div></div></section>
<section className="editorial-section wrap" id="framework"><div className="section-heading"><span className="eyebrow">01 / Beyond the right answer</span><h2>What can you do?<br/><span>How do you decide?</span></h2></div><div className="steps"><article><span className="step-number">01</span><h3>Demonstrate your skill.</h3><p>Write a prompt. Critique an output. Design a workflow. The framework combines structured questions with open-ended tasks that reveal how you think.</p></article><article><span className="step-number">02</span><h3>Meet the right challenge.</h3><p>Question difficulty adapts to your responses, while coverage across all seven domains keeps the assessment broader than your strongest skill.</p></article><article><span className="step-number">03</span><h3>Leave with direction.</h3><p>The report is designed to connect a competency profile with explained strengths, growth areas, learning resources, and a guide to the next level.</p></article></div></section>
<section className="domains-section wrap"><div className="domains-intro"><span className="eyebrow">02 / The whole practitioner</span><h2>More than<br/><em>prompting.</em></h2><p>Seven domains bring knowledge, applied skill, and professional judgment into one picture.</p></div><div className="domain-list">{domains.map(([title,body],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
<section className="editorial-section wrap"><div className="section-heading"><span className="eyebrow">03 / A progression in agency</span><h2>From using outputs<br/><span>to shaping systems.</span></h2></div><div className="levels">{levels.map(([n,title,body])=><article key={n}><span className="level-num">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="development-note">These personas describe stages of practice, not fixed identities. The framework is a formative development tool; pilot calibration and validation are still planned. It is not designed for hiring, performance reviews, or credentialing.</p><a className="text-link" href="/documents/assess-framework.md" download>Download the framework overview <ArrowDown size={18}/></a></section>
<Link href="/composer" className="cross-project wrap"><div><span className="eyebrow">Explore the other project</span><h2>Turn expertise into experience.<br/><em>Meet Composer.</em></h2></div><ArrowUpRight size={44}/></Link></main><Footer/></>}
