import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, ArrowDown, ArrowLeft } from 'lucide-react';
import { Header, Footer, ShapeDiagram } from '../site-components';
export const metadata:Metadata={title:'Composer — An engine for learning',description:'An open-source MCP course authoring engine, designed for AI agents. Separate content from presentation and put human judgment at the center. In development.'};
const steps=[['01','You set the intent.','Bring a lesson plan, a policy, a transcript, or a subject you know well. Define what learners should be able to do.'],['02','The agent authors.','An AI agent structures the lesson and calls Composer’s tools to create, revise, style, and render the course.'],['03','You shape the result.','Review the preview, compare presentations, and give precise feedback. Approved content stays protected.']];
export default function Composer(){return <><Header active="composer"/><main id="main"><section className="detail-hero wrap composer-hero"><Link href="/" className="back-link"><ArrowLeft size={15}/> All projects</Link><div className="detail-title-row"><span className="eyebrow">01 / Composer</span><span className="status"><i/> Design stage · Not yet released</span></div><div className="detail-grid"><div><h1>An engine for<br/><em>learning.</em></h1><p className="detail-lead">What Blender is to 3D content, Composer aims to be for e-learning: an open engine for creating rich, interactive experiences.</p><a className="button ink" href="#how-it-works">Inside Composer <ArrowDown size={18}/></a></div><div className="detail-visual"><span className="eyebrow">CONTENT ≠ PRESENTATION</span><ShapeDiagram/><p>One structure. Many learning experiences.</p></div></div><div className="detail-meta"><span>OPEN SOURCE / MIT</span><span>MCP SERVER</span><span>BUILT FOR AI AGENTS</span></div></section>
<section className="editorial-section wrap" id="how-it-works"><div className="section-heading"><span className="eyebrow">01 / A different way to author</span><h2>You bring the expertise.<br/><span>The agent does the assembly.</span></h2></div><div className="steps">{steps.map(([n,title,body])=><article key={n}><span className="step-number">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="feature-section wrap"><div><span className="eyebrow">02 / The core idea</span><h2>Content has a structure.<br/><em>Give it room to move.</em></h2><p>A term and its definition are a pair. They can become a flashcard, a glossary entry, or a matching exercise. Composer’s design keeps that content independent of its presentation, so “show it differently” doesn’t mean starting over.</p><a className="text-link" href="/documents/composer-overview.md" download>Download the project overview <ArrowDown size={18}/></a></div><div className="stance-list"><div><span>01 / Expository</span><strong>Read it.</strong></div><div><span>02 / Exploratory</span><strong>Explore it.</strong></div><div><span>03 / Practice</span><strong>Try it.</strong></div><div><span>04 / Assessment</span><strong>Demonstrate it.</strong></div></div></section>
<section className="editorial-section wrap design-notes"><div className="section-heading"><span className="eyebrow">03 / Designed from the ground up</span><h2>A course engine.<br/><span>An open foundation.</span></h2></div><div className="detail-list"><article><span>01</span><h3>Tools are the interface.</h3><p>Composer is an MCP server. The agent reasons about the lesson; the engine validates, stores, and renders it. Human effort stays focused on intent and judgment.</p></article><article><span>02</span><h3>Learning comes first.</h3><p>The proposed model starts with 15 content shapes and four learner stances. Structure, interaction, and presentation work together to make content useful to the learner.</p></article><article><span>03</span><h3>Room to extend.</h3><p>New presentations can reuse existing content. The design also allows new shapes, shared interaction behaviors, and generated-media briefs that follow a course-wide style.</p></article></div><p className="development-note">Composer is currently in design. These are the architectural principles and intended capabilities; a released authoring engine is still ahead.</p></section>
<Link href="/assess" className="cross-project wrap"><div><span className="eyebrow">Explore the other project</span><h2>Find your next edge.<br/><em>Meet Assess.</em></h2></div><ArrowUpRight size={44}/></Link></main><Footer/></>}
